datasource:
  url: jdbc:h2:mem:testdb

spring:
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true

security:
  enable-csrf: false
  headers:
    frame: false
  basic:
    enabled: false


